# GümüşDil -> Python Transpiler Output
# Auto-generated by GümüşIDE

sayi = 10
isim = "Ufuk"
def topla(a, b):
    return a + b

if sayi > 5:
    print("Sayı büyük: " + topla(sayi, 5))
else:
    print("Sayı küçük")
